<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="用户登录接口"
           tests="7"
           failures="3"
           errors="0"
           skipped="0"
           time="12.202">
  <properties />
            <testcase name="Case4" time="1.283" classname="TestCases.Login">
                <failure type="java.lang.AssertionError"
                  message="msg =&gt;Expected 【密码不能为空】 but found 【null】"
              >
<![CDATA[java.lang.AssertionError: msg =>Expected 【密码不能为空】 but found 【null】
  org.testng.Assert.fail(Assert.java:94)
  com.jmoney.luckeylink.handler.Login_Handler.checkEquals(Login_Handler.java:312)
  com.jmoney.luckeylink.handler.Login_Handler.Login(Login_Handler.java:288)
  TestCases.Login.Case4(Login.java:33)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="Case2" time="1.406" classname="TestCases.Login">
                <failure type="java.lang.AssertionError"
                  message="msg =&gt;Expected 【账号和密码不能为空】 but found 【null】"
              >
<![CDATA[java.lang.AssertionError: msg =>Expected 【账号和密码不能为空】 but found 【null】
  org.testng.Assert.fail(Assert.java:94)
  com.jmoney.luckeylink.handler.Login_Handler.checkEquals(Login_Handler.java:312)
  com.jmoney.luckeylink.handler.Login_Handler.Login(Login_Handler.java:288)
  TestCases.Login.Case2(Login.java:23)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
            <testcase name="Case3" time="1.288" classname="TestCases.Login">
                <failure type="java.lang.AssertionError"
                  message="msg =&gt;Expected 【账号不能为空】 but found 【null】"
              >
<![CDATA[java.lang.AssertionError: msg =>Expected 【账号不能为空】 but found 【null】
  org.testng.Assert.fail(Assert.java:94)
  com.jmoney.luckeylink.handler.Login_Handler.checkEquals(Login_Handler.java:312)
  com.jmoney.luckeylink.handler.Login_Handler.Login(Login_Handler.java:288)
  TestCases.Login.Case3(Login.java:28)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
  org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="Case1" time="4.077" classname="TestCases.Login" />
                <testcase name="Case6" time="1.372" classname="TestCases.Login" />
                <testcase name="Case7" time="1.340" classname="TestCases.Login" />
                <testcase name="Case5" time="1.436" classname="TestCases.Login" />
      
</testsuite>
